export const FETCH_STATIONS = "FETCH_STATIONS";
export const FETCH_STATIONS_SUCCESS = "FETCH_STATIONS_SUCCESS";
export const FETCH_STATIONS_FAILURE = "FETCH_STATIONS_FAILURE";
export const FETCH_STATION = "FETCH_STATION";
export const TOGGLE_STSTION = "TOGGLE_STSTION";
